Update Jenkinsfile_auotest_example
Pipeline Test

diff --git a/Jenkinsfile_auotest_example b/Jenkinsfile_auotest_example
--- a/Jenkinsfile_auotest_example
+++ b/Jenkinsfile_auotest_example
@@ -31,7 +31,7 @@ pipeline {
                     rm -f $HOME/.android/adbkey*
                     touch $HOME/.android/adbkey
                     touch $HOME/.android/adbkey.pub
-                    chown -R jenkins:jenkins $HOME/.android
+                    chmod -R u+rw $HOME/.android
 
                     runuser -u jenkins -- nohup xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" \
                         $ANDROID_HOME/emulator/emulator -avd jenkins_emulator \
@@ -174,7 +174,7 @@ pipeline {
                 if [ -f emulator_id.txt ]; then
                     emulator_id=$(cat emulator_id.txt)
                     echo "🛑 Stopping emulator $emulator_id"
-                    adb -s "$emulator_id" emu kill || echo "⚠️ Failed to stop emulator"
+                    runuser -u jenkins -- adb -s "$emulator_id" emu kill || echo "⚠️ Failed to stop emulator"
                 fi
             '''
         }
